//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESupplierPresentation.ConsumeJaxWs {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicios/", ConfigurationName="ConsumeJaxWs.WsSoapQueryAuction")]
    public interface WsSoapQueryAuction {
        
        // CODEGEN: El parámetro 'entity' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://servicios/WsSoapQueryAuction/remove")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        void remove(ESupplierPresentation.ConsumeJaxWs.remove1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://servicios/WsSoapQueryAuction/remove")]
        System.Threading.Tasks.Task removeAsync(ESupplierPresentation.ConsumeJaxWs.remove1 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/countRequest", ReplyAction="http://servicios/WsSoapQueryAuction/countResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESupplierPresentation.ConsumeJaxWs.countResponse1 count(ESupplierPresentation.ConsumeJaxWs.countRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/countRequest", ReplyAction="http://servicios/WsSoapQueryAuction/countResponse")]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.countResponse1> countAsync(ESupplierPresentation.ConsumeJaxWs.countRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/findRequest", ReplyAction="http://servicios/WsSoapQueryAuction/findResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESupplierPresentation.ConsumeJaxWs.findResponse1 find(ESupplierPresentation.ConsumeJaxWs.findRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/findRequest", ReplyAction="http://servicios/WsSoapQueryAuction/findResponse")]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findResponse1> findAsync(ESupplierPresentation.ConsumeJaxWs.findRequest request);
        
        // CODEGEN: El parámetro 'entity' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://servicios/WsSoapQueryAuction/create")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        void create(ESupplierPresentation.ConsumeJaxWs.create1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://servicios/WsSoapQueryAuction/create")]
        System.Threading.Tasks.Task createAsync(ESupplierPresentation.ConsumeJaxWs.create1 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/findAllRequest", ReplyAction="http://servicios/WsSoapQueryAuction/findAllResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESupplierPresentation.ConsumeJaxWs.findAllResponse findAll(ESupplierPresentation.ConsumeJaxWs.findAllRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/findAllRequest", ReplyAction="http://servicios/WsSoapQueryAuction/findAllResponse")]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findAllResponse> findAllAsync(ESupplierPresentation.ConsumeJaxWs.findAllRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/findRangeRequest", ReplyAction="http://servicios/WsSoapQueryAuction/findRangeResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESupplierPresentation.ConsumeJaxWs.findRangeResponse findRange(ESupplierPresentation.ConsumeJaxWs.findRangeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/findRangeRequest", ReplyAction="http://servicios/WsSoapQueryAuction/findRangeResponse")]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findRangeResponse> findRangeAsync(ESupplierPresentation.ConsumeJaxWs.findRangeRequest request);
        
        // CODEGEN: El parámetro 'entity' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://servicios/WsSoapQueryAuction/edit")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        void edit(ESupplierPresentation.ConsumeJaxWs.edit1 request);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://servicios/WsSoapQueryAuction/edit")]
        System.Threading.Tasks.Task editAsync(ESupplierPresentation.ConsumeJaxWs.edit1 request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/getAcutionByDatesRequest", ReplyAction="http://servicios/WsSoapQueryAuction/getAcutionByDatesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(edit))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(find))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(getAcutionByDates))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(findAll))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(remove))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(create))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(countResponse))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(count))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesResponse getAcutionByDates(ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicios/WsSoapQueryAuction/getAcutionByDatesRequest", ReplyAction="http://servicios/WsSoapQueryAuction/getAcutionByDatesResponse")]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesResponse> getAcutionByDatesAsync(ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class auction : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auctionsuplier[] auctionsuplierListField;
        
        private bid[] bidListField;
        
        private System.DateTime closedateField;
        
        private bool closedateFieldSpecified;
        
        private long idauctionField;
        
        private bool idauctionFieldSpecified;
        
        private usuario iduserField;
        
        private product[] productListField;
        
        private System.DateTime startdateField;
        
        private bool startdateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auctionsuplierList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public auctionsuplier[] auctionsuplierList {
            get {
                return this.auctionsuplierListField;
            }
            set {
                this.auctionsuplierListField = value;
                this.RaisePropertyChanged("auctionsuplierList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bidList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public bid[] bidList {
            get {
                return this.bidListField;
            }
            set {
                this.bidListField = value;
                this.RaisePropertyChanged("bidList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime closedate {
            get {
                return this.closedateField;
            }
            set {
                this.closedateField = value;
                this.RaisePropertyChanged("closedate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool closedateSpecified {
            get {
                return this.closedateFieldSpecified;
            }
            set {
                this.closedateFieldSpecified = value;
                this.RaisePropertyChanged("closedateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long idauction {
            get {
                return this.idauctionField;
            }
            set {
                this.idauctionField = value;
                this.RaisePropertyChanged("idauction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idauctionSpecified {
            get {
                return this.idauctionFieldSpecified;
            }
            set {
                this.idauctionFieldSpecified = value;
                this.RaisePropertyChanged("idauctionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public usuario iduser {
            get {
                return this.iduserField;
            }
            set {
                this.iduserField = value;
                this.RaisePropertyChanged("iduser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("productList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public product[] productList {
            get {
                return this.productListField;
            }
            set {
                this.productListField = value;
                this.RaisePropertyChanged("productList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime startdate {
            get {
                return this.startdateField;
            }
            set {
                this.startdateField = value;
                this.RaisePropertyChanged("startdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startdateSpecified {
            get {
                return this.startdateFieldSpecified;
            }
            set {
                this.startdateFieldSpecified = value;
                this.RaisePropertyChanged("startdateSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class auctionsuplier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auction auctionField;
        
        private auctionsuplierPK auctionsuplierPKField;
        
        private string offerField;
        
        private suplier suplierField;
        
        private short winField;
        
        private bool winFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auction auction {
            get {
                return this.auctionField;
            }
            set {
                this.auctionField = value;
                this.RaisePropertyChanged("auction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public auctionsuplierPK auctionsuplierPK {
            get {
                return this.auctionsuplierPKField;
            }
            set {
                this.auctionsuplierPKField = value;
                this.RaisePropertyChanged("auctionsuplierPK");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string offer {
            get {
                return this.offerField;
            }
            set {
                this.offerField = value;
                this.RaisePropertyChanged("offer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public suplier suplier {
            get {
                return this.suplierField;
            }
            set {
                this.suplierField = value;
                this.RaisePropertyChanged("suplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public short win {
            get {
                return this.winField;
            }
            set {
                this.winField = value;
                this.RaisePropertyChanged("win");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool winSpecified {
            get {
                return this.winFieldSpecified;
            }
            set {
                this.winFieldSpecified = value;
                this.RaisePropertyChanged("winSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class auctionsuplierPK : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idauctionField;
        
        private long idsuplierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long idauction {
            get {
                return this.idauctionField;
            }
            set {
                this.idauctionField = value;
                this.RaisePropertyChanged("idauction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long idsuplier {
            get {
                return this.idsuplierField;
            }
            set {
                this.idsuplierField = value;
                this.RaisePropertyChanged("idsuplier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class edit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auction entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auction entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class findResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auction returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auction @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class find : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class getAcutionByDates : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fechaInicioField;
        
        private string fechaFinField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fechaInicio {
            get {
                return this.fechaInicioField;
            }
            set {
                this.fechaInicioField = value;
                this.RaisePropertyChanged("fechaInicio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
                this.RaisePropertyChanged("fechaFin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class findAll : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class remove : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auction entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auction entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class create : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auction entityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auction entity {
            get {
                return this.entityField;
            }
            set {
                this.entityField = value;
                this.RaisePropertyChanged("entity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class countResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int returnField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int @return {
            get {
                return this.returnField;
            }
            set {
                this.returnField = value;
                this.RaisePropertyChanged("return");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class count : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string detailField;
        
        private auction idauctionField;
        
        private long idproductField;
        
        private bool idproductFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string detail {
            get {
                return this.detailField;
            }
            set {
                this.detailField = value;
                this.RaisePropertyChanged("detail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public auction idauction {
            get {
                return this.idauctionField;
            }
            set {
                this.idauctionField = value;
                this.RaisePropertyChanged("idauction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public long idproduct {
            get {
                return this.idproductField;
            }
            set {
                this.idproductField = value;
                this.RaisePropertyChanged("idproduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idproductSpecified {
            get {
                return this.idproductFieldSpecified;
            }
            set {
                this.idproductFieldSpecified = value;
                this.RaisePropertyChanged("idproductSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class usuario : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auction[] auctionListField;
        
        private long iduserField;
        
        private bool iduserFieldSpecified;
        
        private string passwordField;
        
        private suplier[] suplierListField;
        
        private string tipoField;
        
        private string usuario1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auctionList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public auction[] auctionList {
            get {
                return this.auctionListField;
            }
            set {
                this.auctionListField = value;
                this.RaisePropertyChanged("auctionList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long iduser {
            get {
                return this.iduserField;
            }
            set {
                this.iduserField = value;
                this.RaisePropertyChanged("iduser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool iduserSpecified {
            get {
                return this.iduserFieldSpecified;
            }
            set {
                this.iduserFieldSpecified = value;
                this.RaisePropertyChanged("iduserSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("suplierList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public suplier[] suplierList {
            get {
                return this.suplierListField;
            }
            set {
                this.suplierListField = value;
                this.RaisePropertyChanged("suplierList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("usuario", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string usuario1 {
            get {
                return this.usuario1Field;
            }
            set {
                this.usuario1Field = value;
                this.RaisePropertyChanged("usuario1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class suplier : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auctionsuplier[] auctionsuplierListField;
        
        private bid[] bidListField;
        
        private string emailField;
        
        private long idsuplierField;
        
        private bool idsuplierFieldSpecified;
        
        private usuario iduserField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("auctionsuplierList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public auctionsuplier[] auctionsuplierList {
            get {
                return this.auctionsuplierListField;
            }
            set {
                this.auctionsuplierListField = value;
                this.RaisePropertyChanged("auctionsuplierList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bidList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public bid[] bidList {
            get {
                return this.bidListField;
            }
            set {
                this.bidListField = value;
                this.RaisePropertyChanged("bidList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public long idsuplier {
            get {
                return this.idsuplierField;
            }
            set {
                this.idsuplierField = value;
                this.RaisePropertyChanged("idsuplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idsuplierSpecified {
            get {
                return this.idsuplierFieldSpecified;
            }
            set {
                this.idsuplierFieldSpecified = value;
                this.RaisePropertyChanged("idsuplierSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public usuario iduser {
            get {
                return this.iduserField;
            }
            set {
                this.iduserField = value;
                this.RaisePropertyChanged("iduser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://servicios/")]
    public partial class bid : object, System.ComponentModel.INotifyPropertyChanged {
        
        private auction idauctionField;
        
        private long idbidField;
        
        private bool idbidFieldSpecified;
        
        private suplier idsuplierField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public auction idauction {
            get {
                return this.idauctionField;
            }
            set {
                this.idauctionField = value;
                this.RaisePropertyChanged("idauction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long idbid {
            get {
                return this.idbidField;
            }
            set {
                this.idbidField = value;
                this.RaisePropertyChanged("idbid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idbidSpecified {
            get {
                return this.idbidFieldSpecified;
            }
            set {
                this.idbidFieldSpecified = value;
                this.RaisePropertyChanged("idbidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public suplier idsuplier {
            get {
                return this.idsuplierField;
            }
            set {
                this.idsuplierField = value;
                this.RaisePropertyChanged("idsuplier");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="remove", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class remove1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESupplierPresentation.ConsumeJaxWs.auction entity;
        
        public remove1() {
        }
        
        public remove1(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="count", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class countRequest {
        
        public countRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="countResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class countResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public countResponse1() {
        }
        
        public countResponse1(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="find", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class findRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object id;
        
        public findRequest() {
        }
        
        public findRequest(object id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class findResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESupplierPresentation.ConsumeJaxWs.auction @return;
        
        public findResponse1() {
        }
        
        public findResponse1(ESupplierPresentation.ConsumeJaxWs.auction @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class create1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESupplierPresentation.ConsumeJaxWs.auction entity;
        
        public create1() {
        }
        
        public create1(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAll", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class findAllRequest {
        
        public findAllRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findAllResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class findAllResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESupplierPresentation.ConsumeJaxWs.auction[] @return;
        
        public findAllResponse() {
        }
        
        public findAllResponse(ESupplierPresentation.ConsumeJaxWs.auction[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRange", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class findRangeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("range", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<int>[] range;
        
        public findRangeRequest() {
        }
        
        public findRangeRequest(System.Nullable<int>[] range) {
            this.range = range;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findRangeResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class findRangeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESupplierPresentation.ConsumeJaxWs.auction[] @return;
        
        public findRangeResponse() {
        }
        
        public findRangeResponse(ESupplierPresentation.ConsumeJaxWs.auction[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="edit", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class edit1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESupplierPresentation.ConsumeJaxWs.auction entity;
        
        public edit1() {
        }
        
        public edit1(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            this.entity = entity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAcutionByDates", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class getAcutionByDatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaInicio;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fechaFin;
        
        public getAcutionByDatesRequest() {
        }
        
        public getAcutionByDatesRequest(string fechaInicio, string fechaFin) {
            this.fechaInicio = fechaInicio;
            this.fechaFin = fechaFin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getAcutionByDatesResponse", WrapperNamespace="http://servicios/", IsWrapped=true)]
    public partial class getAcutionByDatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://servicios/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ESupplierPresentation.ConsumeJaxWs.auction[] @return;
        
        public getAcutionByDatesResponse() {
        }
        
        public getAcutionByDatesResponse(ESupplierPresentation.ConsumeJaxWs.auction[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WsSoapQueryAuctionChannel : ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WsSoapQueryAuctionClient : System.ServiceModel.ClientBase<ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction>, ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction {
        
        public WsSoapQueryAuctionClient() {
        }
        
        public WsSoapQueryAuctionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WsSoapQueryAuctionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapQueryAuctionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WsSoapQueryAuctionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.remove(ESupplierPresentation.ConsumeJaxWs.remove1 request) {
            base.Channel.remove(request);
        }
        
        public void remove(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            ESupplierPresentation.ConsumeJaxWs.remove1 inValue = new ESupplierPresentation.ConsumeJaxWs.remove1();
            inValue.entity = entity;
            ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).remove(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.removeAsync(ESupplierPresentation.ConsumeJaxWs.remove1 request) {
            return base.Channel.removeAsync(request);
        }
        
        public System.Threading.Tasks.Task removeAsync(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            ESupplierPresentation.ConsumeJaxWs.remove1 inValue = new ESupplierPresentation.ConsumeJaxWs.remove1();
            inValue.entity = entity;
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).removeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESupplierPresentation.ConsumeJaxWs.countResponse1 ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.count(ESupplierPresentation.ConsumeJaxWs.countRequest request) {
            return base.Channel.count(request);
        }
        
        public int count() {
            ESupplierPresentation.ConsumeJaxWs.countRequest inValue = new ESupplierPresentation.ConsumeJaxWs.countRequest();
            ESupplierPresentation.ConsumeJaxWs.countResponse1 retVal = ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).count(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.countResponse1> ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.countAsync(ESupplierPresentation.ConsumeJaxWs.countRequest request) {
            return base.Channel.countAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.countResponse1> countAsync() {
            ESupplierPresentation.ConsumeJaxWs.countRequest inValue = new ESupplierPresentation.ConsumeJaxWs.countRequest();
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).countAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESupplierPresentation.ConsumeJaxWs.findResponse1 ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.find(ESupplierPresentation.ConsumeJaxWs.findRequest request) {
            return base.Channel.find(request);
        }
        
        public ESupplierPresentation.ConsumeJaxWs.auction find(object id) {
            ESupplierPresentation.ConsumeJaxWs.findRequest inValue = new ESupplierPresentation.ConsumeJaxWs.findRequest();
            inValue.id = id;
            ESupplierPresentation.ConsumeJaxWs.findResponse1 retVal = ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).find(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findResponse1> ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.findAsync(ESupplierPresentation.ConsumeJaxWs.findRequest request) {
            return base.Channel.findAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findResponse1> findAsync(object id) {
            ESupplierPresentation.ConsumeJaxWs.findRequest inValue = new ESupplierPresentation.ConsumeJaxWs.findRequest();
            inValue.id = id;
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).findAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.create(ESupplierPresentation.ConsumeJaxWs.create1 request) {
            base.Channel.create(request);
        }
        
        public void create(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            ESupplierPresentation.ConsumeJaxWs.create1 inValue = new ESupplierPresentation.ConsumeJaxWs.create1();
            inValue.entity = entity;
            ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).create(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.createAsync(ESupplierPresentation.ConsumeJaxWs.create1 request) {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task createAsync(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            ESupplierPresentation.ConsumeJaxWs.create1 inValue = new ESupplierPresentation.ConsumeJaxWs.create1();
            inValue.entity = entity;
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESupplierPresentation.ConsumeJaxWs.findAllResponse ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.findAll(ESupplierPresentation.ConsumeJaxWs.findAllRequest request) {
            return base.Channel.findAll(request);
        }
        
        public ESupplierPresentation.ConsumeJaxWs.auction[] findAll() {
            ESupplierPresentation.ConsumeJaxWs.findAllRequest inValue = new ESupplierPresentation.ConsumeJaxWs.findAllRequest();
            ESupplierPresentation.ConsumeJaxWs.findAllResponse retVal = ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).findAll(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findAllResponse> ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.findAllAsync(ESupplierPresentation.ConsumeJaxWs.findAllRequest request) {
            return base.Channel.findAllAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findAllResponse> findAllAsync() {
            ESupplierPresentation.ConsumeJaxWs.findAllRequest inValue = new ESupplierPresentation.ConsumeJaxWs.findAllRequest();
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).findAllAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESupplierPresentation.ConsumeJaxWs.findRangeResponse ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.findRange(ESupplierPresentation.ConsumeJaxWs.findRangeRequest request) {
            return base.Channel.findRange(request);
        }
        
        public ESupplierPresentation.ConsumeJaxWs.auction[] findRange(System.Nullable<int>[] range) {
            ESupplierPresentation.ConsumeJaxWs.findRangeRequest inValue = new ESupplierPresentation.ConsumeJaxWs.findRangeRequest();
            inValue.range = range;
            ESupplierPresentation.ConsumeJaxWs.findRangeResponse retVal = ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).findRange(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findRangeResponse> ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.findRangeAsync(ESupplierPresentation.ConsumeJaxWs.findRangeRequest request) {
            return base.Channel.findRangeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.findRangeResponse> findRangeAsync(System.Nullable<int>[] range) {
            ESupplierPresentation.ConsumeJaxWs.findRangeRequest inValue = new ESupplierPresentation.ConsumeJaxWs.findRangeRequest();
            inValue.range = range;
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).findRangeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.edit(ESupplierPresentation.ConsumeJaxWs.edit1 request) {
            base.Channel.edit(request);
        }
        
        public void edit(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            ESupplierPresentation.ConsumeJaxWs.edit1 inValue = new ESupplierPresentation.ConsumeJaxWs.edit1();
            inValue.entity = entity;
            ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).edit(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.editAsync(ESupplierPresentation.ConsumeJaxWs.edit1 request) {
            return base.Channel.editAsync(request);
        }
        
        public System.Threading.Tasks.Task editAsync(ESupplierPresentation.ConsumeJaxWs.auction entity) {
            ESupplierPresentation.ConsumeJaxWs.edit1 inValue = new ESupplierPresentation.ConsumeJaxWs.edit1();
            inValue.entity = entity;
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).editAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesResponse ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.getAcutionByDates(ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest request) {
            return base.Channel.getAcutionByDates(request);
        }
        
        public ESupplierPresentation.ConsumeJaxWs.auction[] getAcutionByDates(string fechaInicio, string fechaFin) {
            ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest inValue = new ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesResponse retVal = ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).getAcutionByDates(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesResponse> ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction.getAcutionByDatesAsync(ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest request) {
            return base.Channel.getAcutionByDatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesResponse> getAcutionByDatesAsync(string fechaInicio, string fechaFin) {
            ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest inValue = new ESupplierPresentation.ConsumeJaxWs.getAcutionByDatesRequest();
            inValue.fechaInicio = fechaInicio;
            inValue.fechaFin = fechaFin;
            return ((ESupplierPresentation.ConsumeJaxWs.WsSoapQueryAuction)(this)).getAcutionByDatesAsync(inValue);
        }
    }
}
